---
title: "DifTU"
author: 
  - "Katie Kelly"
  - "Eugene Hickey"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = FALSE,
  message = FALSE, 
  warning = FALSE,
  fig.show = TRUE,
  hiline = TRUE
)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
library(tidyverse)
library(likert)
library(showtext)
library(ggtext)
style_duo_accent(
  primary_color = "#1381B0",
  secondary_color = "#FF961C",
  inverse_header_color = "#FFFFFF"
)
# style_mono_accent(
#   base_color = "#6E8B3D",               # olive green
#   inverse_background_color = "#002B36", # dark dark blue
#   inverse_header_color = "#31b09e",     # light aqua green
#   inverse_text_color = "#FFFFFF",       # white
#   title_slide_background_color = "var(--base)",
#   text_font_google = google_font("Neucha"),
#   header_font_google = google_font("Neucha"),
#   text_font_size = "12px",
#   base_font_size = "12px"
# )
```

```{r fonts-and-themes, cache=TRUE}
font_add_google("Neucha", "Neucha")

showtext_auto()

```

```{r data-in, cache = TRUE}
student_index <- read_csv("../data/student-index-tidy.csv") %>% 
  select(Campus, everything()) %>% 
  mutate(survey = "Index - 2019")
student_diftu <- read_csv("../data/student-diftu-tidy.csv") %>% 
  select(-c(Other, DTLkeep)) %>% 
  select(-c(QualityL:none_access)) %>% 
  mutate(survey = "DifTU - 2021")


student <- bind_rows(student_diftu, student_index)


student_model <- student %>% 
  mutate_if(is.character,as.factor) %>% 
  mutate(Years = fct_relevel(Years, levels = c("Less than a year", "1-2 years", "2-3 years", "More than 3 years")),
         FindInfo = fct_relevel(FindInfo, levels = c("Daily", "Weekly or more", "Monthly or less", "Never")),
         Workonline = fct_relevel(Workonline, levels = c("Daily", "Weekly or more", "Monthly or less", "Never")),
         Useeducationalgame = fct_relevel(Useeducationalgame, levels = c("Daily", "Weekly or more", "Monthly or less", "Never")),
         UsePolling = fct_relevel(UsePolling, levels = c("Daily", "Weekly or more", "Monthly or less", "Never")),
         Cr8DigPortfolio = fct_relevel(Cr8DigPortfolio, levels = c("Daily", "Weekly or more", "Monthly or less", "Never")),
         Usepptword = fct_relevel(Usepptword, levels = c("Daily", "Weekly or more", "Monthly or less", "Never")),
         Reference = fct_relevel(Reference, levels = c("Daily", "Weekly or more", "Monthly or less", "Never")),
         StudyTimwe = fct_relevel(StudyTimwe, levels = c("Daily", "Weekly or more", "Monthly or less", "Never")),
         NotesT = fct_relevel(NotesT, levels = c("Daily", "Weekly or more", "Monthly or less", "Never")),
         AdditionalResources = fct_relevel(AdditionalResources, levels = c("Daily", "Weekly or more", "Monthly or less", "Never")),
         AccessLectures = fct_relevel(AccessLectures, levels = c("Daily", "Weekly or more", "Monthly or less", "Never")),
         AccessLectures = fct_relevel(AccessLectures, levels = c("Agree", "Neutral", "Disagree")),
         InstSupport = fct_relevel(InstSupport, levels = c("Agree", "Neutral", "Disagree")),
         InstHealth = fct_relevel(InstHealth, levels = c("Agree", "Neutral", "Disagree")),
         SocietyAccess = fct_relevel(SocietyAccess, levels = c("Agree", "Neutral", "Disagree")),
         DataPrivacy = fct_relevel(DataPrivacy, levels = c("Agree", "Neutral", "Disagree")),
         VLEeasyuse = fct_relevel(VLEeasyuse, levels = c("Agree", "Neutral", "Disagree")),
         Vlereliable = fct_relevel(Vlereliable, levels = c("Agree", "Neutral", "Disagree")),
         Vlemobile = fct_relevel(Vlemobile, levels = c("Agree", "Neutral", "Disagree")),
         Vleusebylecturers = fct_relevel(Vleusebylecturers, levels = c("Agree", "Neutral", "Disagree")),
         Onlineassesments = fct_relevel(Onlineassesments, levels = c("Agree", "Neutral", "Disagree")),
         GoodTeachingSpaces = fct_relevel(GoodTeachingSpaces, levels = c("Agree", "Neutral", "Disagree")),
         RelevantSoftware = fct_relevel(RelevantSoftware, levels = c("Agree", "Neutral", "Disagree")),
         PersoalDataStorage = fct_relevel(PersoalDataStorage, levels = c("Agree", "Neutral", "Disagree")),
         DigitalSkill4Jobs = fct_relevel(DigitalSkill4Jobs, levels = c("Agree", "Neutral", "Disagree")),
         Opp2updateDSkills = fct_relevel(Opp2updateDSkills, levels = c("Agree", "Neutral", "Disagree")),
         DSkillsneededinCareer = fct_relevel(DSkillsneededinCareer, levels = c("Agree", "Neutral", "Disagree")),
         Dworkplaceprep = fct_relevel(Dworkplaceprep, levels = c("Agree", "Neutral", "Disagree")),
         InvolinDskillsdecisions = fct_relevel(InvolinDskillsdecisions, levels = c("Agree", "Neutral", "Disagree")),
         BetterUndertstanding = fct_relevel(BetterUndertstanding, levels = c("Agree", "Neutral", "Disagree")),
         Enjoymore = fct_relevel(Enjoymore, levels = c("Agree", "Neutral", "Disagree")),
         Independent = fct_relevel(Independent, levels = c("Agree", "Neutral", "Disagree")),
         Fitseasily = fct_relevel(Fitseasily, levels = c("Agree", "Neutral", "Disagree")))

```


```{r q17, fig.height=5}
likert <- student_model %>%
  as.data.frame %>% 
  select(FindInfo:Usepptword, survey) %>% 
  drop_na() 

likert %>% 
  select(FindInfo:Usepptword) %>% 
  rename("Work online with others" = Workonline,
         "Create a digital record/ portfolio of your learning" = Cr8DigPortfolio,
         "Find information online" = FindInfo,
         "Use an educational game or simulation learning" = Useeducationalgame,
         "Use a polling device / online quiz to give answers in class" = UsePolling,
         "Produce work in digital formats other than Word/PowerPoint" = Usepptword) %>% 
  likert(grouping = likert %>% pull(survey)) %>% 
  plot(ordered = F, wrap= 60, labeller = labels) + 
  labs(title = "As part of your course, how often do you…")
```

---

```{r q12, fig.height=5}
likert <- student_model %>%
  as.data.frame %>% 
  select(Reference:AccessLectures, survey) %>% 
  drop_na() 

likert %>% 
  select(Reference:AccessLectures) %>%
  rename("Manage links or references" = Reference,
         "Organise your study time" = StudyTimwe,
         "Make notes or recordings" = NotesT,
         "Access lecture notes or recorded lectures" = AccessLectures,
         "Look for extra resources not recommended by your lecturer" = AdditionalResources) %>% 
  likert(grouping = likert %>% pull(survey)) %>% 
  plot(ordered = F, wrap= 60, labeller = labels) + 
  labs(title = "In your own learning time, how often do you use digital tools or apps to…")
```

---

```{r q14, fig.height=5}
# Question 14
likert <- student_model %>%
  as.data.frame %>% 
  select(InstSupport:DataPrivacy, survey) %>% 
  drop_na() 

likert %>% 
  select(InstSupport:DataPrivacy) %>%
  rename("This institution supports me to use my own digital devices" = InstSupport,
         "I can access institution health and wellbeing services online" = InstHealth,
         "I can participate in student union / club / society activities online" = SocietyAccess,
         "This institution protects my data privacy" = DataPrivacy) %>% 
  likert(grouping = likert %>% pull(survey)) %>% 
  plot(ordered = F, wrap= 60, labeller = labels) + 
  labs(title = "How much do you agree with the following statements?")
```

---

```{r q18, fig.height=5}
# Question 18
likert <- student_model %>%
  as.data.frame %>% 
  select(VLEeasyuse:Vleusebylecturers, survey) %>% 
  drop_na() 

likert %>% 
  select(VLEeasyuse:Vleusebylecturers) %>%
  rename("I can easily find things on the VLE" = VLEeasyuse,
         "I rely on it to do my coursework" = Vlereliable,
         "I regularly access it on a mobile device" = Vlemobile,
         "I would like it to be used more by my tutors/instructors" = Vleusebylecturers) %>% 
  likert(grouping = likert %>% pull(survey)) %>% 
  plot(ordered = F, wrap= 60, labeller = labels) + 
  labs(title = "How much do you agree with the following statements?")
```


---

```{r q19, fig.height=5}
# Question 19
likert <- student_model %>%
  as.data.frame %>% 
  select(Onlineassesments:PersoalDataStorage, survey) %>% 
  drop_na() 

likert %>% 
  select(Onlineassesments:PersoalDataStorage) %>%
  rename("Online assessments are delivered and managed well" = Onlineassesments,
         "Teaching spaces are well designed for the technologies we use" = GoodTeachingSpaces,
         "The software used on my course is industry standard and up-to-date" = RelevantSoftware,
         "I am told how my personal data is stored and used" = PersoalDataStorage) %>% 
  likert(grouping = likert %>% pull(survey)) %>% 
  plot(ordered = F, wrap= 60, labeller = labels) + 
  labs(title = "How much do you agree with the following statements?")
```


---

```{r q20, fig.height=5}
# Question 20
likert <- student_model %>%
  as.data.frame %>% 
  select(DigitalSkill4Jobs:InvolinDskillsdecisions, survey) %>% 
  drop_na() 

likert %>% 
  select(DigitalSkill4Jobs:InvolinDskillsdecisions) %>%
  rename("Before I started my course I was told what digital skills I would need" = DigitalSkill4Jobs,
         "I have regular opportunities to review and update my digital skills" = Opp2updateDSkills,
         "Digital skills are important in my chosen career" = DSkillsneededinCareer,
         "My course prepares me for the digital workplace" = Dworkplaceprep,
         "Learners are given the chance to be involved in decisions about digital services" = InvolinDskillsdecisions) %>% 
  likert(grouping = likert %>% pull(survey)) %>% 
  plot(ordered = F, wrap= 60, labeller = labels) + 
  labs(title = "How much do you agree with the following statements?")
```

---

```{r q24, fig.height=5}
# Question 24
likert <- student_model %>%
  as.data.frame %>% 
  select(BetterUndertstanding:Fitseasily, survey) %>% 
  drop_na() 

likert %>% 
  select(BetterUndertstanding:Fitseasily) %>%
  rename("I understand things better" = BetterUndertstanding,
         "I enjoy learning more" = Enjoymore,
         "I am more independent in my learning" = Independent,
         "I can fit learning into my life more easily" = Fitseasily) %>% 
  likert(grouping = likert %>% pull(survey)) %>% 
  plot(ordered = F, wrap= 60, labeller = labels) + 
  labs(title = "When digital technologies are used on my course ...")
```